added hw
Vicktoria2011/JS-Lectures-hw-02.10 pull request #1
Opened 2023-10-02 08:57 UTC by Vicktoria2011

2023-10-02 14:42 UTC, DmytroSanitarskyi requested changes

2023-10-02 14:42 UTC, DmytroSanitarskyi commented on lection/hw.js
> +//3
Напишіть конструкцію if, щоб перевіряє, чи значення ціни товару не знаходиться між 1000 та 1900 включно.
    Реалізуйте два варіанти, один з оператором НЕ !, а інший без цього оператора.
    Результат виводити в консоль.
    
    Має бути два варіанти

2023-10-02 14:42 UTC, DmytroSanitarskyi commented on lection/hw.js
> +if(a > b && b > c){
потрібно було використати вкладені оператори

```
if (a > b) {
    if (a > c) {
        // a - max
        if (b > c)
        avg = b
        else
        avg = c
    }
```

2023-10-11 19:09 UTC, SanitarskyiDmytro approved these changes

2023-10-15 08:07 UTC, merged